forge "https://forgeapi.puppetlabs.com"

mod 'rodjek-logrotate',      '1.1.1'
mod 'puppetlabs/postgresql', '4.5.0'
mod 'puppetlabs-rabbitmq',   '5.2.3'
mod 'stahnma-epel',          '1.0.2'

mod 'covermymeds-herqles',
  :git => 'https://github.com/herqles-io/puppet-herqles.git'